/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RootLayoutRouteImport } from './routes/_root-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContributionsRouteImport } from './routes/api/contributions'
import { Route as RootLayoutHomeRouteImport } from './routes/_root-layout/home'

const RootLayoutRoute = RootLayoutRouteImport.update({
  id: '/_root-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributionsRoute = ApiContributionsRouteImport.update({
  id: '/api/contributions',
  path: '/api/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutHomeRoute = RootLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => RootLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof RootLayoutHomeRoute
  '/api/contributions': typeof ApiContributionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof RootLayoutHomeRoute
  '/api/contributions': typeof ApiContributionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_root-layout': typeof RootLayoutRouteWithChildren
  '/_root-layout/home': typeof RootLayoutHomeRoute
  '/api/contributions': typeof ApiContributionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/api/contributions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/api/contributions'
  id:
    | '__root__'
    | '/'
    | '/_root-layout'
    | '/_root-layout/home'
    | '/api/contributions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
  ApiContributionsRoute: typeof ApiContributionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_root-layout': {
      id: '/_root-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributions': {
      id: '/api/contributions'
      path: '/api/contributions'
      fullPath: '/api/contributions'
      preLoaderRoute: typeof ApiContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root-layout/home': {
      id: '/_root-layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof RootLayoutHomeRouteImport
      parentRoute: typeof RootLayoutRoute
    }
  }
}

interface RootLayoutRouteChildren {
  RootLayoutHomeRoute: typeof RootLayoutHomeRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutHomeRoute: RootLayoutHomeRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootLayoutRoute: RootLayoutRouteWithChildren,
  ApiContributionsRoute: ApiContributionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
